spring:
 application:
  name: store-service
  
server:
 port: 9000
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost  