zuul:
  prefix: /api
  routes:
   store-service:
    path: /store/**
    serviceId: STORE-SERVICE
   inventory-service:
    path: /inventory/**
    serviceId: INVENTORY-SERVICE
    
spring:
 application:
  name: zuul-service
  
server:
 port: 8079
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  hostname: localhost
  
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  
  